initial commit for adding fast bottleneck
NVIDIA/apex pull request #1079
Opened 2021-04-16 11:11 UTC by FDecaYed

2021-04-16 16:05 UTC, thorjohnsen commented
We need this MR in 21.05 for mlperf 1.0. I have verified that it compiles for master-py3-devel image and it is protected by a flag in setup.py, so the risk is low.

2021-04-16 17:19 UTC, cliffwoolley commented on apex/contrib/csrc/bottleneck/bottleneck.cpp
> + * all copies or substantial portions of the Software.
This is MIT license.  APEX should be under BSD 3-clause license https://github.com/NVIDIA/apex/blob/master/LICENSE .  (And a header like this should be in all the files, not just this one.)

2021-04-16 17:23 UTC, cliffwoolley requested changes
License headers need to be correct.

2021-04-16 17:28 UTC, cliffwoolley commented
@seryilmaz Please review.

2021-04-16 18:43 UTC, matthew-frank approved these changes
Cliff asked for an additional review.  On a quick perusal this looks good to me, but I didn't do any very careful checking.

2021-04-16 19:53 UTC, seryilmaz commented
This looks good to me. Deyu may not be able to add license headers soon since he is offline due to his timezone.

2021-04-16 20:32 UTC, mcarilli commented
Will this break import of apex in general if the extension is not built?

2021-04-17 00:24 UTC, ptrblck commented
@mcarilli No, importing apex is working without the `--fast_bottleneck` option (checked it locally).
PR is also building with the last commit.

2021-04-17 00:24 UTC, ptrblck approved these changes

2021-04-17 00:24 UTC, merged