Add the warning of distributed_fused_adam low bucket usage
NVIDIA/apex pull request #1714
Opened 2023-08-23 12:37 UTC by shjwudp

If not set a fit bucket size in the distributed optimizer, memory waste will result. Memory loss is sometimes high but invisible, for example, a 10GB penalty on a misconfigured gpt-7b. I think reporting a warning when the bucket utilization is low is a solution, and I submitted my code as reference.

2023-08-23 17:32 UTC, timmoon10 requested changes
This would be a very useful check. I just have a suggestion to handle the case where the parameters are initialized in multiple stages, e.g. if the user uses `init_params_bucket` to manually configure buckets.

2023-08-24 01:48 UTC, shjwudp commented
Hi Tim, It's great to see your reply! I appreciate your help in correcting it; thanks!

2023-08-24 23:14 UTC, timmoon10 approved these changes
LGTM. Thanks!

2023-08-28 20:48 UTC, crcrpar approved these changes

2023-08-28 20:49 UTC, merged